import { StateTariff } from '../types/resourceCenter.types';

export const STATE_TARIFF_MOCK_DATA: StateTariff[] = [
  { stateCode: 'MH', month: 1, state: 'Maharashtra', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '33kV', tod: 'TOD1', todName: 'Morning Peak', season: 'Summer', todStartHour: '06:00', todEndHour: '09:00', baseEnergyCharges: 5.5000, todRate: 1.2000, energyCharges: 6.7000 },
  { stateCode: 'MH', month: 1, state: 'Maharashtra', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '33kV', tod: 'TOD2', todName: 'Normal', season: 'Summer', todStartHour: '09:00', todEndHour: '18:00', baseEnergyCharges: 5.5000, todRate: 0.0000, energyCharges: 5.5000 },
  { stateCode: 'MH', month: 1, state: 'Maharashtra', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '33kV', tod: 'TOD3', todName: 'Evening Peak', season: 'Summer', todStartHour: '18:00', todEndHour: '22:00', baseEnergyCharges: 5.5000, todRate: 1.5000, energyCharges: 7.0000 },
  { stateCode: 'MH', month: 1, state: 'Maharashtra', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '33kV', tod: 'TOD4', todName: 'Night Off-Peak', season: 'Summer', todStartHour: '22:00', todEndHour: '06:00', baseEnergyCharges: 5.5000, todRate: -1.0000, energyCharges: 4.5000 },
  { stateCode: 'GJ', month: 1, state: 'Gujarat', category: 'HT Industry', subCategory: 'General', voltageLevel: '11kV', tod: 'TOD1', todName: 'Morning Peak', season: 'All', todStartHour: '07:00', todEndHour: '11:00', baseEnergyCharges: 5.2000, todRate: 0.8500, energyCharges: 6.0500 },
  { stateCode: 'GJ', month: 1, state: 'Gujarat', category: 'HT Industry', subCategory: 'General', voltageLevel: '11kV', tod: 'TOD2', todName: 'Normal', season: 'All', todStartHour: '11:00', todEndHour: '18:00', baseEnergyCharges: 5.2000, todRate: 0.0000, energyCharges: 5.2000 },
  { stateCode: 'GJ', month: 1, state: 'Gujarat', category: 'HT Industry', subCategory: 'General', voltageLevel: '11kV', tod: 'TOD3', todName: 'Evening Peak', season: 'All', todStartHour: '18:00', todEndHour: '22:00', baseEnergyCharges: 5.2000, todRate: 1.0000, energyCharges: 6.2000 },
  { stateCode: 'GJ', month: 1, state: 'Gujarat', category: 'HT Industry', subCategory: 'General', voltageLevel: '11kV', tod: 'TOD4', todName: 'Night Off-Peak', season: 'All', todStartHour: '22:00', todEndHour: '07:00', baseEnergyCharges: 5.2000, todRate: -0.5000, energyCharges: 4.7000 },
  { stateCode: 'KA', month: 1, state: 'Karnataka', category: 'HT Industry', subCategory: 'General', voltageLevel: '66kV', tod: 'TOD1', todName: 'Morning Peak', season: 'All', todStartHour: '06:00', todEndHour: '10:00', baseEnergyCharges: 5.8000, todRate: 1.0000, energyCharges: 6.8000 },
  { stateCode: 'KA', month: 1, state: 'Karnataka', category: 'HT Industry', subCategory: 'General', voltageLevel: '66kV', tod: 'TOD2', todName: 'Normal', season: 'All', todStartHour: '10:00', todEndHour: '18:00', baseEnergyCharges: 5.8000, todRate: 0.0000, energyCharges: 5.8000 },
  { stateCode: 'KA', month: 1, state: 'Karnataka', category: 'HT Industry', subCategory: 'General', voltageLevel: '66kV', tod: 'TOD3', todName: 'Evening Peak', season: 'All', todStartHour: '18:00', todEndHour: '22:00', baseEnergyCharges: 5.8000, todRate: 1.5000, energyCharges: 7.3000 },
  { stateCode: 'KA', month: 1, state: 'Karnataka', category: 'HT Industry', subCategory: 'General', voltageLevel: '66kV', tod: 'TOD4', todName: 'Night Off-Peak', season: 'All', todStartHour: '22:00', todEndHour: '06:00', baseEnergyCharges: 5.8000, todRate: -1.0000, energyCharges: 4.8000 },
  { stateCode: 'TN', month: 1, state: 'Tamil Nadu', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '110kV', tod: 'TOD1', todName: 'Morning Peak', season: 'All', todStartHour: '06:00', todEndHour: '10:00', baseEnergyCharges: 6.2000, todRate: 1.2500, energyCharges: 7.4500 },
  { stateCode: 'TN', month: 1, state: 'Tamil Nadu', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '110kV', tod: 'TOD2', todName: 'Normal', season: 'All', todStartHour: '10:00', todEndHour: '18:00', baseEnergyCharges: 6.2000, todRate: 0.0000, energyCharges: 6.2000 },
  { stateCode: 'TN', month: 1, state: 'Tamil Nadu', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '110kV', tod: 'TOD3', todName: 'Evening Peak', season: 'All', todStartHour: '18:00', todEndHour: '22:00', baseEnergyCharges: 6.2000, todRate: 1.5500, energyCharges: 7.7500 },
];
