import { StateTariff } from '../types/resourceCenter.types';

export const STATE_TARIFF_MOCK_DATA: StateTariff[] = [
  { id: 1, state: 'Uttar Pradesh', consumerCategory: 'LMV-11', subCategory: 'Multistoried Buildings (Common Usage)', supplyVoltageCategory: 'Low Tension (LT)', supplyVoltage: '—', month: 202604, todStartTime: '—', todEndTime: '—', baseEnergyRate: 6.2, baseEnergyUnit: 'kWh', todChargePercent: 0, energyRate: 6.2, updatedAt: new Date().toISOString() },
  { id: 2, state: 'Uttar Pradesh', consumerCategory: 'LMV-11', subCategory: 'Multistoried Buildings (Common Usage)', supplyVoltageCategory: 'High Tension (HT)', supplyVoltage: '—', month: 202604, todStartTime: '—', todEndTime: '—', baseEnergyRate: 5.9, baseEnergyUnit: 'kWh', todChargePercent: 0, energyRate: 5.9, updatedAt: new Date().toISOString() },
  { id: 3, state: 'Uttar Pradesh', consumerCategory: 'LMV-11', subCategory: 'Public Charging, BaaS, Swapping Stations', supplyVoltageCategory: 'Low Tension (LT)', supplyVoltage: '—', month: 202604, todStartTime: '9:00', todEndTime: '16:00', baseEnergyRate: 6.16, baseEnergyUnit: 'kWh', todChargePercent: -20, energyRate: 4.928, updatedAt: new Date().toISOString() },
  { id: 4, state: 'Uttar Pradesh', consumerCategory: 'LMV-11', subCategory: 'Public Charging, BaaS, Swapping Stations', supplyVoltageCategory: 'Low Tension (LT)', supplyVoltage: '—', month: 202604, todStartTime: '16:00', todEndTime: '9:00', baseEnergyRate: 7.7, baseEnergyUnit: 'kWh', todChargePercent: 0, energyRate: 7.7, updatedAt: new Date().toISOString() },
  { id: 5, state: 'Uttar Pradesh', consumerCategory: 'HV-1', subCategory: 'Commercial, Private Inst., Non-Domestic Bulk (>=75 kW)', supplyVoltageCategory: 'At 11 kV', supplyVoltage: '11', month: 202604, todStartTime: '—', todEndTime: '—', baseEnergyRate: 8.32, baseEnergyUnit: 'kVAh', todChargePercent: 0, energyRate: 8.32, updatedAt: new Date().toISOString() },
  { id: 6, state: 'Uttar Pradesh', consumerCategory: 'HV-2', subCategory: 'Urban Schedule (Large & Heavy Power)', supplyVoltageCategory: 'Up to 11 kV', supplyVoltage: '11', month: 202604, todStartTime: '5:00', todEndTime: '10:00', baseEnergyRate: 6.035, baseEnergyUnit: 'kVAh', todChargePercent: -15, energyRate: 5.12975, updatedAt: new Date().toISOString() },
  { id: 7, state: 'Uttar Pradesh', consumerCategory: 'HV-2', subCategory: 'Urban Schedule (Large & Heavy Power)', supplyVoltageCategory: 'Up to 11 kV', supplyVoltage: '11', month: 202604, todStartTime: '10:00', todEndTime: '19:00', baseEnergyRate: 7.1, baseEnergyUnit: 'kVAh', todChargePercent: 0, energyRate: 7.1, updatedAt: new Date().toISOString() },
  { id: 8, state: 'Uttar Pradesh', consumerCategory: 'HV-2', subCategory: 'Urban Schedule (Large & Heavy Power)', supplyVoltageCategory: 'Up to 11 kV', supplyVoltage: '11', month: 202604, todStartTime: '19:00', todEndTime: '3:00', baseEnergyRate: 8.165, baseEnergyUnit: 'kVAh', todChargePercent: 15, energyRate: 9.38975, updatedAt: new Date().toISOString() },
];

