import { StuCharges } from '../types/resourceCenter.types';

export const STU_CHARGES_MOCK_DATA: StuCharges[] = [
  { stateCode: 'MH', state: 'Maharashtra', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '33kV', month: 1, stuChargesRsPerKwh: 1.2500, demandCharges: 400, percentFppaCharges: 5.5, additionalCharges: 0.1500, crossSubsidy: 1.5000, distributionWheelingChargesRsPerKwh: 0.8500, stuLossPercent: 3.2, distributionWheelingLossPercent: 6.5 },
  { stateCode: 'MH', state: 'Maharashtra', category: 'HT Industry', subCategory: 'Non-Continuous', voltageLevel: '33kV', month: 1, stuChargesRsPerKwh: 1.2500, demandCharges: 350, percentFppaCharges: 5.5, additionalCharges: 0.1500, crossSubsidy: 1.3500, distributionWheelingChargesRsPerKwh: 0.8500, stuLossPercent: 3.2, distributionWheelingLossPercent: 6.5 },
  { stateCode: 'GJ', state: 'Gujarat', category: 'HT Industry', subCategory: 'General', voltageLevel: '11kV', month: 1, stuChargesRsPerKwh: 1.1500, demandCharges: 300, percentFppaCharges: 4.8, additionalCharges: 0.1000, crossSubsidy: 1.2000, distributionWheelingChargesRsPerKwh: 0.7500, stuLossPercent: 3.0, distributionWheelingLossPercent: 5.8 },
  { stateCode: 'GJ', state: 'Gujarat', category: 'Commercial', subCategory: 'General', voltageLevel: '11kV', month: 1, stuChargesRsPerKwh: 1.1500, demandCharges: 450, percentFppaCharges: 4.8, additionalCharges: 0.1000, crossSubsidy: 1.8000, distributionWheelingChargesRsPerKwh: 0.7500, stuLossPercent: 3.0, distributionWheelingLossPercent: 5.8 },
  { stateCode: 'KA', state: 'Karnataka', category: 'HT Industry', subCategory: 'General', voltageLevel: '66kV', month: 1, stuChargesRsPerKwh: 1.3500, demandCharges: 380, percentFppaCharges: 6.0, additionalCharges: 0.2000, crossSubsidy: 1.6000, distributionWheelingChargesRsPerKwh: 0.9500, stuLossPercent: 3.5, distributionWheelingLossPercent: 7.0 },
  { stateCode: 'TN', state: 'Tamil Nadu', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '110kV', month: 1, stuChargesRsPerKwh: 1.4500, demandCharges: 420, percentFppaCharges: 6.5, additionalCharges: 0.2500, crossSubsidy: 1.7000, distributionWheelingChargesRsPerKwh: 1.0500, stuLossPercent: 3.8, distributionWheelingLossPercent: 7.5 },
  { stateCode: 'TN', state: 'Tamil Nadu', category: 'Commercial', subCategory: 'General', voltageLevel: '110kV', month: 1, stuChargesRsPerKwh: 1.4500, demandCharges: 500, percentFppaCharges: 6.5, additionalCharges: 0.2500, crossSubsidy: 2.0000, distributionWheelingChargesRsPerKwh: 1.0500, stuLossPercent: 3.8, distributionWheelingLossPercent: 7.5 },
  { stateCode: 'AP', state: 'Andhra Pradesh', category: 'HT Industry', subCategory: 'General', voltageLevel: '33kV', month: 1, stuChargesRsPerKwh: 1.3000, demandCharges: 360, percentFppaCharges: 5.8, additionalCharges: 0.1800, crossSubsidy: 1.4500, distributionWheelingChargesRsPerKwh: 0.9000, stuLossPercent: 3.3, distributionWheelingLossPercent: 6.8 },
  { stateCode: 'TS', state: 'Telangana', category: 'HT Industry', subCategory: 'General', voltageLevel: '33kV', month: 1, stuChargesRsPerKwh: 1.2800, demandCharges: 370, percentFppaCharges: 5.6, additionalCharges: 0.1600, crossSubsidy: 1.4000, distributionWheelingChargesRsPerKwh: 0.8800, stuLossPercent: 3.1, distributionWheelingLossPercent: 6.6 },
  { stateCode: 'UP', state: 'Uttar Pradesh', category: 'HT Industry', subCategory: 'Continuous', voltageLevel: '132kV', month: 1, stuChargesRsPerKwh: 1.5000, demandCharges: 450, percentFppaCharges: 7.0, additionalCharges: 0.3000, crossSubsidy: 1.8500, distributionWheelingChargesRsPerKwh: 1.1000, stuLossPercent: 4.0, distributionWheelingLossPercent: 8.0 },
  { stateCode: 'UP', state: 'Uttar Pradesh', category: 'Commercial', subCategory: 'General', voltageLevel: '132kV', month: 1, stuChargesRsPerKwh: 1.5000, demandCharges: 550, percentFppaCharges: 7.0, additionalCharges: 0.3000, crossSubsidy: 2.2000, distributionWheelingChargesRsPerKwh: 1.1000, stuLossPercent: 4.0, distributionWheelingLossPercent: 8.0 },
  { stateCode: 'MP', state: 'Madhya Pradesh', category: 'HT Industry', subCategory: 'General', voltageLevel: '33kV', month: 1, stuChargesRsPerKwh: 1.2000, demandCharges: 330, percentFppaCharges: 5.0, additionalCharges: 0.1200, crossSubsidy: 1.3000, distributionWheelingChargesRsPerKwh: 0.8000, stuLossPercent: 3.0, distributionWheelingLossPercent: 6.0 },
  { stateCode: 'RJ', state: 'Rajasthan', category: 'HT Industry', subCategory: 'General', voltageLevel: '33kV', month: 1, stuChargesRsPerKwh: 1.4000, demandCharges: 410, percentFppaCharges: 6.2, additionalCharges: 0.2200, crossSubsidy: 1.6500, distributionWheelingChargesRsPerKwh: 1.0000, stuLossPercent: 3.6, distributionWheelingLossPercent: 7.2 },
  { stateCode: 'PB', state: 'Punjab', category: 'HT Industry', subCategory: 'General', voltageLevel: '66kV', month: 1, stuChargesRsPerKwh: 1.2200, demandCharges: 340, percentFppaCharges: 5.2, additionalCharges: 0.1400, crossSubsidy: 1.3500, distributionWheelingChargesRsPerKwh: 0.8200, stuLossPercent: 3.1, distributionWheelingLossPercent: 6.2 },
  { stateCode: 'HR', state: 'Haryana', category: 'HT Industry', subCategory: 'General', voltageLevel: '66kV', month: 1, stuChargesRsPerKwh: 1.2400, demandCharges: 350, percentFppaCharges: 5.4, additionalCharges: 0.1600, crossSubsidy: 1.4000, distributionWheelingChargesRsPerKwh: 0.8400, stuLossPercent: 3.2, distributionWheelingLossPercent: 6.4 },
];
