export const REGION_STATE_MOCK_DATA = [
  { regionalGrid: 'Eastern', regionCode: 'ER', regionName: 'Eastern', stateName: 'Jharkhand', stateCode: 'JH', stateOrUt: 'State' },
  { regionalGrid: 'Eastern', regionCode: 'ER', regionName: 'Eastern', stateName: 'Odisha', stateCode: 'OD', stateOrUt: 'State' },
  { regionalGrid: 'Eastern', regionCode: 'ER', regionName: 'Eastern', stateName: 'West Bengal', stateCode: 'WB', stateOrUt: 'State' },
  { regionalGrid: 'Eastern', regionCode: 'ER', regionName: 'Eastern', stateName: 'Bihar', stateCode: 'BR', stateOrUt: 'State' },
  { regionalGrid: 'North Eastern', regionCode: 'NER', regionName: 'North Eastern', stateName: 'Assam', stateCode: 'AS', stateOrUt: 'State' },
  { regionalGrid: 'North Eastern', regionCode: 'NER', regionName: 'North Eastern', stateName: 'Meghalaya', stateCode: 'ML', stateOrUt: 'State' },
  { regionalGrid: 'Northern', regionCode: 'NR', regionName: 'Northern', stateName: 'Delhi', stateCode: 'DL', stateOrUt: 'UT' },
  { regionalGrid: 'Northern', regionCode: 'NR', regionName: 'Northern', stateName: 'Chandigarh', stateCode: 'CH', stateOrUt: 'UT' },
  { regionalGrid: 'Southern', regionCode: 'SR', regionName: 'Southern', stateName: 'Tamil Nadu', stateCode: 'TN', stateOrUt: 'State' },
  { regionalGrid: 'Southern', regionCode: 'SR', regionName: 'Southern', stateName: 'Karnataka', stateCode: 'KA', stateOrUt: 'State' },
  { regionalGrid: 'Western', regionCode: 'WR', regionName: 'Western', stateName: 'Maharashtra', stateCode: 'MH', stateOrUt: 'State' },
  { regionalGrid: 'Western', regionCode: 'WR', regionName: 'Western', stateName: 'Gujarat', stateCode: 'GJ', stateOrUt: 'State' },
  { regionalGrid: 'Northern', regionCode: 'NR', regionName: 'Northern', stateName: 'Haryana', stateCode: 'HR', stateOrUt: 'State' },
  { regionalGrid: 'Northern', regionCode: 'NR', regionName: 'Northern', stateName: 'Punjab', stateCode: 'PB', stateOrUt: 'State' },
  { regionalGrid: 'Southern', regionCode: 'SR', regionName: 'Southern', stateName: 'Kerala', stateCode: 'KL', stateOrUt: 'State' },
  { regionalGrid: 'Southern', regionCode: 'SR', regionName: 'Southern', stateName: 'Andhra Pradesh', stateCode: 'AP', stateOrUt: 'State' },
  { regionalGrid: 'Western', regionCode: 'WR', regionName: 'Western', stateName: 'Madhya Pradesh', stateCode: 'MP', stateOrUt: 'State' },
];
