import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { GitBranch, Download, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatCurrency } from "@/lib/calculatorUtils";

interface OASettlementSankeyProps {
  discomCharges: number;
  oaEnergyCharges: number;
  transmissionCharges: number;
  totalBill: number;
  anomalies?: string[];
}

export function OASettlementSankey({
  discomCharges,
  oaEnergyCharges,
  transmissionCharges,
  totalBill,
  anomalies = [],
}: OASettlementSankeyProps) {
  const flows = [
    { 
      source: 'DISCOM Charges', 
      value: discomCharges, 
      color: 'hsl(217 55% 50%)',
      items: ['Energy Charges', 'Fixed Charges', 'PPAC', 'Electricity Duty']
    },
    { 
      source: 'OA Energy', 
      value: oaEnergyCharges, 
      color: 'hsl(175 55% 40%)',
      items: ['IEX Purchase', 'Trading Margin', 'Scheduling Charges']
    },
    { 
      source: 'Transmission', 
      value: transmissionCharges, 
      color: 'hsl(142 55% 50%)',
      items: ['STU/SLDC', 'CTU/NLDC', 'Wheeling', 'Losses']
    },
  ];

  const handleDownload = () => {
    // Create settlement bill content
    const content = `
OA SETTLEMENT BILL
==================
Generated: ${new Date().toLocaleDateString()}

CHARGE BREAKDOWN
----------------
DISCOM Charges: ${formatCurrency(discomCharges)}
  - Energy Charges
  - Fixed Charges
  - PPAC
  - Electricity Duty

OA Energy Charges: ${formatCurrency(oaEnergyCharges)}
  - IEX Purchase
  - Trading Margin
  - Scheduling Charges

Transmission Charges: ${formatCurrency(transmissionCharges)}
  - STU/SLDC
  - CTU/NLDC
  - Wheeling
  - Losses

TOTAL BILL: ${formatCurrency(totalBill)}

${anomalies.length > 0 ? `
ANOMALIES DETECTED
------------------
${anomalies.map(a => `• ${a}`).join('\n')}
` : ''}
==================
Generated by Prolt Energy Platform
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'oa-settlement-bill.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Card className="border-0 shadow-lg">
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg flex items-center gap-2">
              <GitBranch className="w-5 h-5 text-accent" />
              How Your OA Bill Was Settled
            </CardTitle>
            <p className="text-sm text-muted-foreground">
              Multi-panel breakdown of charges and settlement
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={handleDownload} className="gap-2">
            <Download className="w-4 h-4" />
            Download Bill
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {/* Simplified Sankey-style flow visualization */}
        <div className="space-y-4">
          {flows.map((flow, index) => (
            <div key={index} className="flex items-stretch gap-4">
              {/* Source */}
              <div 
                className="w-32 p-3 rounded-lg flex flex-col justify-center"
                style={{ backgroundColor: `${flow.color}20`, borderLeft: `3px solid ${flow.color}` }}
              >
                <p className="text-sm font-medium text-foreground">{flow.source}</p>
                <p className="text-lg font-bold" style={{ color: flow.color }}>
                  {formatCurrency(flow.value)}
                </p>
              </div>
              
              {/* Flow arrow */}
              <div className="flex-1 flex items-center">
                <div 
                  className="h-2 flex-1 rounded-full relative"
                  style={{ backgroundColor: `${flow.color}30` }}
                >
                  <div 
                    className="h-full rounded-full transition-all duration-500"
                    style={{ 
                      width: `${(flow.value / totalBill) * 100}%`,
                      backgroundColor: flow.color
                    }}
                  />
                </div>
                <div 
                  className="w-0 h-0 border-t-[8px] border-t-transparent border-b-[8px] border-b-transparent border-l-[12px] ml-1"
                  style={{ borderLeftColor: flow.color }}
                />
              </div>
              
              {/* Items */}
              <div className="w-40">
                {flow.items.map((item, i) => (
                  <p key={i} className="text-xs text-muted-foreground">• {item}</p>
                ))}
              </div>
            </div>
          ))}
        </div>
        
        {/* Total */}
        <div className="mt-6 p-4 bg-accent/10 rounded-lg flex items-center justify-between">
          <span className="text-sm font-medium">Total Consumer Bill</span>
          <span className="text-2xl font-bold text-accent">{formatCurrency(totalBill)}</span>
        </div>
        
        {/* Anomalies */}
        {anomalies.length > 0 && (
          <div className="mt-4 p-3 bg-yellow-500/10 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <AlertTriangle className="w-4 h-4 text-yellow-500" />
              <span className="text-sm font-medium text-yellow-500">Anomalies Detected</span>
            </div>
            <ul className="space-y-1">
              {anomalies.map((anomaly, i) => (
                <li key={i} className="text-xs text-muted-foreground">• {anomaly}</li>
              ))}
            </ul>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
